server:
  port: 8091
spring:
  application:
    name: "Orders"
  devtools:
    add-properties: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://db_orders:5432/orders   #db_orders - localhost
    user: postgres
    password: root
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    path: /api/doc/api-docs
  swagger-ui:
    path: /api/doc/swagger-ui.html
adapters:
  r2dbc:
    host: db_orders                #db_orders - localhost
    port: 5432
    database: orders
    schema: "public"
    username: postgres
    password: root
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8091"
logging:
  level:
    root: INFO
  file:
    name: logs/crediya_orders.log